# Uncomment the next line to define a global platform for your project
 platform :ios, '15.0'

target 'Urgent' do
  # Comment the next line if you don't want to use dynamic frameworks
pod 'GoogleMaps'
pod 'GooglePlaces'
pod 'Google-Maps-iOS-Utils'
pod 'Google-Mobile-Ads-SDK'
pod "Cluster"
pod "lottie-ios"
pod "KakaoSDKNavi"

#  use_frameworks!

  # Pods for Urgent

  target 'UrgentTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UrgentUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
